-- Generated by scripts/generate-seed-sql.mjs from data/seed-questions.json — do not edit by hand.
-- Seeds the initial question bank and schedules rounds for the next 30 days (UTC).

INSERT INTO questions (id, question_text, hint, correct_lat, correct_lng, correct_label, category, difficulty)
VALUES
  ('5eed0000-0000-4000-8000-000000000001', 'Where is the Melbourne Cricket Ground (MCG)?', 'Australia''s biggest stadium, home of the Boxing Day Test', -37.82, 144.9834, 'Melbourne, Australia', 'stadium', 'easy'),
  ('5eed0000-0000-4000-8000-000000000002', 'Where was the 2011 ICC Cricket World Cup final held?', 'Dhoni finished it with a six into the stands', 18.9389, 72.8258, 'Wankhede Stadium, Mumbai, India', 'world_cup', 'medium'),
  ('5eed0000-0000-4000-8000-000000000003', 'Where is Lord''s Cricket Ground — the ''Home of Cricket''?', 'St John''s Wood', 51.5294, -0.1728, 'London, England', 'stadium', 'easy'),
  ('5eed0000-0000-4000-8000-000000000004', 'Where was Sachin Tendulkar born?', 'The same city he''d later win a World Cup in', 19.0176, 72.8562, 'Mumbai, India', 'birthplace', 'easy'),
  ('5eed0000-0000-4000-8000-000000000005', 'Where is the Galle International Stadium?', 'Overlooked by a 17th-century Dutch fort', 6.0322, 80.215, 'Galle, Sri Lanka', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000006', 'Where was the famous 1999 World Cup semi-final tie between Australia and South Africa?', 'Allan Donald''s run-out in the English Midlands', 52.4558, -1.9025, 'Edgbaston, Birmingham, England', 'historic_match', 'hard'),
  ('5eed0000-0000-4000-8000-000000000007', 'Where is the Eden Gardens stadium?', 'On the banks of the Hooghly', 22.5646, 88.3433, 'Kolkata, India', 'stadium', 'easy'),
  ('5eed0000-0000-4000-8000-000000000008', 'Where was Sir Donald Bradman born?', 'A country town in New South Wales', -34.6411, 148.0281, 'Cootamundra, NSW, Australia', 'birthplace', 'hard'),
  ('5eed0000-0000-4000-8000-000000000009', 'Where is the Kensington Oval?', 'Caribbean island, hosted the 2007 World Cup final', 13.1065, -59.6228, 'Bridgetown, Barbados', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000010', 'Where was the first-ever Test match played in 1877?', 'Australia beat England by 45 runs', -37.82, 144.9834, 'MCG, Melbourne, Australia', 'historic_match', 'medium'),
  ('5eed0000-0000-4000-8000-000000000011', 'Where was Virat Kohli born?', 'India''s capital', 28.6139, 77.209, 'Delhi, India', 'birthplace', 'easy'),
  ('5eed0000-0000-4000-8000-000000000012', 'Where is the Newlands Cricket Ground?', 'In the shadow of Table Mountain', -33.9271, 18.4124, 'Cape Town, South Africa', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000013', 'Where was the 2019 ICC Cricket World Cup final held?', 'Decided on boundary count after a Super Over', 51.5294, -0.1728, 'Lord''s, London, England', 'world_cup', 'easy'),
  ('5eed0000-0000-4000-8000-000000000014', 'Where was Brian Lara born?', 'The southernmost Caribbean nation', 10.7167, -61.4667, 'Santa Cruz, Trinidad', 'birthplace', 'hard'),
  ('5eed0000-0000-4000-8000-000000000015', 'Where is the WACA ground?', 'Famous for its fast, bouncy pitch and the ''Fremantle Doctor''', -31.96, 115.8795, 'Perth, Australia', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000016', 'Where was the 2007 T20 World Cup final held?', 'India beat Pakistan at the ''Bullring''', -26.1325, 28.0607, 'Wanderers Stadium, Johannesburg, South Africa', 'world_cup', 'hard'),
  ('5eed0000-0000-4000-8000-000000000017', 'Where was AB de Villiers born?', 'South Africa''s administrative capital', -25.7479, 28.2293, 'Pretoria, South Africa', 'birthplace', 'medium'),
  ('5eed0000-0000-4000-8000-000000000018', 'Where is the Sharjah Cricket Stadium?', 'Holds the record for most ODIs hosted', 25.3463, 55.4209, 'Sharjah, UAE', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000019', 'Where did India win the 1983 World Cup final?', 'Kapil''s Devils lifted the Prudential Cup at the Home of Cricket', 51.5294, -0.1728, 'Lord''s, London, England', 'world_cup', 'easy'),
  ('5eed0000-0000-4000-8000-000000000020', 'Where was Kumar Sangakkara born?', 'Central Province, north of Kandy', 7.4675, 80.6234, 'Matale, Sri Lanka', 'birthplace', 'hard'),
  ('5eed0000-0000-4000-8000-000000000021', 'Where is the Rawalpindi Cricket Stadium?', 'Twin city of Pakistan''s capital', 33.5965, 73.0551, 'Rawalpindi, Pakistan', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000022', 'Where was the famous ''Tied Test'' of 1960 played?', 'Australia v West Indies in Queensland', -27.4858, 153.0381, 'The Gabba, Brisbane, Australia', 'historic_match', 'hard'),
  ('5eed0000-0000-4000-8000-000000000023', 'Where was Kane Williamson born?', 'Bay of Plenty, North Island', -37.6878, 176.1651, 'Tauranga, New Zealand', 'birthplace', 'hard'),
  ('5eed0000-0000-4000-8000-000000000024', 'Where is the Wanderers Stadium (Bullring)?', 'Scene of the 438 ODI chase in 2006', -26.1325, 28.0607, 'Johannesburg, South Africa', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000025', 'Where was the 2015 World Cup final held?', 'Australia beat New Zealand in front of 93,000', -37.82, 144.9834, 'MCG, Melbourne, Australia', 'world_cup', 'medium'),
  ('5eed0000-0000-4000-8000-000000000026', 'Where was Babar Azam born?', 'Home of the Gaddafi Stadium', 31.5204, 74.3587, 'Lahore, Pakistan', 'birthplace', 'medium'),
  ('5eed0000-0000-4000-8000-000000000027', 'Where is the R Premadasa Stadium?', 'Sri Lanka''s commercial capital', 6.9188, 79.8638, 'Colombo, Sri Lanka', 'stadium', 'medium'),
  ('5eed0000-0000-4000-8000-000000000028', 'Where did Ben Stokes play his famous 135* Ashes innings in 2019?', 'Yorkshire''s Test venue', 53.8175, -1.5823, 'Headingley, Leeds, England', 'historic_match', 'medium'),
  ('5eed0000-0000-4000-8000-000000000029', 'Where was MS Dhoni born?', 'Capital of Jharkhand', 23.3441, 85.3096, 'Ranchi, India', 'birthplace', 'medium'),
  ('5eed0000-0000-4000-8000-000000000030', 'Where is the Dubai International Cricket Stadium?', 'Part of Dubai Sports City', 25.0469, 55.2186, 'Dubai, UAE', 'stadium', 'medium')
ON CONFLICT (id) DO NOTHING;

SELECT generate_daily_rounds((now() AT TIME ZONE 'utc')::date, 30);
